from . import device_type
from . import device_attribute
from . import device_model
from . import device_assignment
from . import device_brand
from . import device
from . import device_management_settings
from . import employee
from . import device_settings
from . import device_attribute_value
